name: Chained Jobs with Skipping

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      fake_output: ${{ steps.set-output.outputs.fake_output }}
    steps:
      - id: set-output
        run: echo "fake_output=false" >> $GITHUB_OUTPUT
      - run: echo "Hello from Job1"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    outputs:
      another_fake_output: ${{ steps.set-output.outputs.another_fake_output }}
    steps:
      - id: set-output
        run: echo "another_fake_output=false" >> $GITHUB_OUTPUT
      - run: echo "Hello from Job2"

  job3:
    needs: job2
    if: needs.job1.outputs.fake_output == 'true'  # This condition will never be met
    uses: ./.github/workflows/skip1.yml
    with:
      github_repo_environment: PRODUCTION_AU
      config_repo: ${{ needs.setup-build.outputs.SERVICE_SETTINGS_REPO }}
      config_repo_ref: ${{ needs.setup-build.outputs.SERVICE_SETTINGS_REPO_REF }}
      svc_config_file_name: ${{ needs.setup-build.outputs.SERVICE_SETTING_JSON_FILE }}
    
    # Define outputs for the entire job (to be used by job4)
    secrets: inherit

  job4:
    needs: job3
    if: needs.job2.outputs.another_fake_output == 'true'  # This condition will never be met
    name: Deploy SKIP_AU
    uses: ./.github/workflows/skip2.yml
    with:
      GITHUB_REPO_ENVIRONMENT: ${{ needs.job3.outputs.AWS }}
