name: Reusable Workflow 2

on:
  workflow_call:
    inputs:
      github_repo_environment:
        type: string
      config_repo:
        type: string
      config_repo_ref:
        type: string
      svc_config_file_name:
        type: string

jobs:
  skip1-job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_repo_environment }}
    steps:
      - run: echo "Running skip1 workflow with config ${{ inputs.svc_config_file_name }}"
